# @package _global_
type: prerender

prerender_method: OPT
data_dir: "datasets/OPT/Model3D"
batch_size: 2
body_names: ['bike', 'chest', 'house', 'ironman', 'jet', 'soda']
sphere_radius: 0.8
maximum_body_diameter: 0.3
geometry_unit_in_meter: 1.0 # 0.001
image_size: 2000
image_border_size: 20
n_divide: 4
normalize_to_origin: False  # fixed False
num_sample_contour_point: 200
k_min_contour_length: 15
k_contour_normal_approx_radius: 3
output_mask: False # True
output_depth: False
output_depth_vertex: False
