# @package _global_
type: prerender

prerender_method: RBOT
data_dir: "datasets/RBOT"
batch_size: 2
body_names: ['ape', 'bakingsoda', 'benchviseblue', 'broccolisoup', 'cam', 'can', 'cat', 'clown', 'cube',
             'driller', 'duck', 'eggbox', 'glue', 'iron', 'koalacandy', 'lamp', 'phone', 'squirrel']
sphere_radius: 0.8
maximum_body_diameter: 0.3
geometry_unit_in_meter: 0.001 # 0.001
image_size: 2000
image_border_size: 20
n_divide: 4
normalize_to_origin: False  # fixed False
num_sample_contour_point: 200
k_min_contour_length: 15
k_contour_normal_approx_radius: 3
output_mask: False
output_depth: False
output_depth_vertex: False