# @package _global_
type: test_deepac
task: tracking

save_dir: ${work_dir}/workspace/test_rbot_deepac
# TODO: change path
load_cfg: ${work_dir}/workspace/train_bop_deepac/logs-2024-01-08-15-52-47/train_cfg.yml
load_model: ${work_dir}/workspace/train_bop_deepac/logs-2024-01-08-15-52-47/model_last.ckpt
# -----------------
output_video: false
output_size: [320, 320]
output_pose: true

fore_learn_rate: 0.2
back_learn_rate: 0.2
gpu_id: '0' # 0, 1
distribution_length: 12

data:
  name: RBOT
  dataset_dir: datasets/RBOT
  change_background: false
  batch_size_per_gpu: 1
  test_obj_names: # ['cube'] 
                ['ape', 'bakingsoda', 'benchviseblue', 'broccolisoup', 'cam', 'can', 'cat', 'clown', 'cube',
                    'driller', 'duck', 'eggbox', 'glue', 'iron', 'koalacandy', 'lamp', 'phone', 'squirrel']
  test_slices: ['a_regular' , 'b_dynamiclight', 'c_noisy', 'd_occlusion']
  # test_slices: ['c_noisy']
  skip_frame: 1
  num_correspondence_lines: 200
  # workers_per_gpu: 0

ray:
  use_ray: true # false
  n_obj_workers: 3
  n_slice_workers: 1
  n_cpus_per_worker: 1
  n_gpus_per_worker: 0.1
